sudo: required
install:
 - echo  weeeeee > /home/travis/build/ang-st/travis-test/fooo.txt
language: node_js
node_js:
- '5.7'
deploy:
  provider: releases
  api_key: "580ffee692a3232dbeece3125229730f46afc071"
  file: "/home/travis/build/ang-st/travis-test/fooo.txt"
  skip_cleanup: true
  on:
    tags: true
