sudo: required
install:
  - npm install electron-packager -g
  - electron-packager app/ foo --platform=linux --arch=x64 --version=0.35.6
  - ls -l  /home/travis/build/ang-st/travis-test/foo-linux-x64
  - tar czf /home/travis/build/ang-st/travis-test/foo-linux-x64.tgz /home/travis/build/ang-st/travis-test/foo-linux-x64
language: node_js
node_js:
- '5.7'
deploy:
  provider: releases
  api_key: "01c4c966fca8ef51e9281b7a19b35f9cb50e3fde"
  file: "/home/travis/build/ang-st/travis-test/foo-linux-x64.tgz"
  skip_cleanup: true
  on:
    tags: true
